name: Deployment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]
    steps:
      - uses: actions/checkout@v2
      - name: NPM CI and generate
        shell: bash
        run: |
          npm ci
          npm run generate
      - name: Check git status
        shell: bash
        run: git status --porcelain
      - name: Add and commit new files
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs -f
          git add .
          git commit -m "Deployment"
          git push origin +main:gh-pages
